### ISSUE TITLE
Per-recipe language

### ISSUE THREAD

**Issue by savissimo** [seeyouspacecorgi/cooklang-obsidian#3]
The current language is currently being read from Obsidian's metadata, which is fine for most uses. Do you think it would be feasible to apply the localization according to the recipe's own metadata? This way, we could allow for recipes in different languages in the same vault. 

A recipe could have something like:

    >> language: it

which indicates that _that recipe_ is in Italian, while others keep their own value or the default one.

**Comment by seeyouspacecorgi** [comment]
I agree it would be a nice feature and totally doable. I've been researching different ways to implement this and I'm leaning towards using settings to define the language. It seems flexible enough to allow assigning a language to a file or folder.

However I think it depends on how you use the plugin. On one hand a set key in the metadatas (which are rendered) means the recipe can't be integrally in the user's language. On the other, settings could be tedious to set up if all recipes are in the same folder.

Maybe allowing both would be the best compromise ?

**Comment by savissimo** [comment]
Is it possible to parse the metadata, in order to 1) exclude some from being displayed, and 2) use the value for the rendering?

**Comment by seeyouspacecorgi** [comment]
Yes it is. 
Metadatas are parsed but not rendered by the plugin, I added a few lines to do that in this fork. Any metadata could either be skipped in render or hidden in css.

**Comment by seeyouspacecorgi** [comment]
The feature has been added with the last merge.
